import { useState } from 'react'
import { FileText, BookOpen, Send, RefreshCw, Copy, Check } from 'lucide-react'
import { usePapers } from '@/hooks/usePapers'
import { usePaperAbstract, useSynthesis } from '@/hooks/useAbstract'
import { cn } from '@/lib/utils'

type Tab = 'per-paper' | 'synthesis'

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const copy = () => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button onClick={copy} className="flex items-center gap-1 text-[12px] text-slate-400 hover:text-slate-600 transition-colors">
      {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? 'Copied' : 'Copy'}
    </button>
  )
}

function PerPaperTab() {
  const { papers, loading } = usePapers()
  const [selectedId, setSelectedId] = useState('')
  const { abstract, loading: abLoading, error, generate } = usePaperAbstract()

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div className="bg-white rounded-2xl p-6 shadow-card border border-slate-100">
        <h2 className="font-semibold text-slate-800 mb-1">Generate Paper Abstract</h2>
        <p className="text-[13px] text-slate-500 mb-4">
          Select a paper and Claude will generate a structured abstract (Objective / Methods / Results / Conclusion).
        </p>

        <div className="flex gap-3">
          <select
            value={selectedId}
            onChange={(e) => setSelectedId(e.target.value)}
            className="flex-1 bg-slate-50 border border-slate-200/60 rounded-xl px-3 py-2.5 text-[13px] text-slate-700 outline-none focus:ring-2 focus:ring-blue-500/20"
          >
            <option value="">Select a paper…</option>
            {!loading && papers.map((p) => (
              <option key={p.paper_id} value={p.paper_id}>
                {p.title} {p.year ? `(${p.year})` : ''}
              </option>
            ))}
          </select>
          <button
            onClick={() => selectedId && generate(selectedId, !!abstract)}
            disabled={!selectedId || abLoading}
            className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-[13px] font-medium rounded-xl hover:shadow-glow disabled:from-slate-300 disabled:to-slate-300 disabled:shadow-none transition-all"
          >
            {abLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
            {abstract ? 'Regenerate' : 'Generate'}
          </button>
        </div>

        {error && (
          <p className="mt-3 text-[12px] text-red-500 bg-red-50 rounded-lg px-3 py-2">{error}</p>
        )}
      </div>

      {abstract && (
        <div className="bg-white rounded-2xl p-6 shadow-card border border-slate-100 animate-fade-in-up">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-slate-800">Structured Abstract</h3>
            <CopyButton
              text={`Objective: ${abstract.objective}\n\nMethods: ${abstract.methods}\n\nResults: ${abstract.results}\n\nConclusion: ${abstract.conclusion}`}
            />
          </div>
          {(['objective', 'methods', 'results', 'conclusion'] as const).map((field) => (
            <div key={field} className="mb-4 last:mb-0">
              <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-1.5 capitalize">
                {field}
              </p>
              <p className="text-[14px] text-slate-700 leading-relaxed">{abstract[field]}</p>
            </div>
          ))}
          <p className="text-[11px] text-slate-400 mt-4 pt-4 border-t border-slate-100">
            Generated by Claude · {abstract.generated_at?.slice(0, 10)}
          </p>
        </div>
      )}
    </div>
  )
}

function SynthesisTab() {
  const [query, setQuery] = useState('')
  const [topK, setTopK] = useState(10)
  const [style, setStyle] = useState<'background' | 'survey' | 'introduction'>('background')
  const { text, citedPapers, isStreaming, error, synthesize, clear } = useSynthesis()

  const handleSubmit = () => {
    if (!query.trim() || isStreaming) return
    clear()
    synthesize(query.trim(), { n_results: topK, style })
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="bg-white rounded-2xl p-6 shadow-card border border-slate-100">
        <h2 className="font-semibold text-slate-800 mb-1">Literature Review Synthesis</h2>
        <p className="text-[13px] text-slate-500 mb-4">
          Enter a topic and Claude will synthesize a paragraph from the most relevant papers —
          ready to paste into your Background / Related Work section.
        </p>

        <textarea
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => { if (e.key === 'Enter' && e.metaKey) handleSubmit() }}
          placeholder="e.g. deep learning methods for 3D pavement crack detection using LiDAR"
          rows={3}
          className="w-full resize-none bg-slate-50 border border-slate-200/60 rounded-xl px-4 py-3 text-[14px] focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-300 transition-all placeholder:text-slate-400 mb-3"
        />

        <div className="flex items-center gap-3 flex-wrap">
          <label className="flex items-center gap-1.5 text-[12px] text-slate-500">
            Top-K papers:
            <input
              type="number" min={3} max={20} value={topK}
              onChange={(e) => setTopK(Number(e.target.value))}
              className="bg-slate-50 border border-slate-200/60 rounded-md px-2 w-14 text-center text-[12px] outline-none focus:ring-2 focus:ring-blue-500/20"
            />
          </label>

          <label className="flex items-center gap-1.5 text-[12px] text-slate-500">
            Style:
            <select
              value={style}
              onChange={(e) => setStyle(e.target.value as typeof style)}
              className="bg-slate-50 border border-slate-200/60 rounded-md px-2 py-1 text-[12px] text-slate-600 outline-none focus:ring-2 focus:ring-blue-500/20"
            >
              <option value="background">Background section</option>
              <option value="survey">Survey overview</option>
              <option value="introduction">Introduction motivation</option>
            </select>
          </label>

          <button
            onClick={handleSubmit}
            disabled={!query.trim() || isStreaming}
            className="ml-auto flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-[13px] font-medium rounded-xl hover:shadow-glow disabled:from-slate-300 disabled:to-slate-300 disabled:shadow-none transition-all"
          >
            {isStreaming ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
            Synthesize
          </button>
        </div>

        {error && (
          <p className="mt-3 text-[12px] text-red-500 bg-red-50 rounded-lg px-3 py-2">{error}</p>
        )}
      </div>

      {(text || isStreaming) && (
        <div className="bg-white rounded-2xl p-6 shadow-card border border-slate-100 animate-fade-in-up">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-slate-800 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-blue-500" />
              Synthesis
              {isStreaming && <span className="text-[11px] text-blue-500 font-normal animate-pulse">Writing…</span>}
            </h3>
            {text && !isStreaming && <CopyButton text={text} />}
          </div>
          <p className="text-[14px] text-slate-700 leading-relaxed whitespace-pre-wrap">{text}</p>
          {isStreaming && (
            <span className="inline-block w-2 h-4 bg-blue-500 animate-pulse ml-0.5 rounded-sm" />
          )}
        </div>
      )}

      {citedPapers.length > 0 && (
        <div className="bg-white rounded-2xl p-6 shadow-card border border-slate-100 animate-fade-in-up">
          <h3 className="font-semibold text-slate-800 mb-3">
            Cited Papers ({citedPapers.length})
          </h3>
          <div className="space-y-2">
            {citedPapers.map((p) => (
              <div key={p.paper_id} className="flex items-center justify-between text-[13px]">
                <span className="text-slate-700 font-medium truncate max-w-[360px]">
                  {p.title} {p.year ? `(${p.year})` : ''}
                </span>
                <div className="flex items-center gap-2 shrink-0">
                  <span className="text-[11px] text-slate-400">{p.category}</span>
                  {p.relevance != null && (
                    <span className="text-[11px] bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full font-medium">
                      {(p.relevance * 100).toFixed(0)}%
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

export default function Abstracts() {
  const [tab, setTab] = useState<Tab>('per-paper')

  return (
    <div className="flex flex-col h-screen">
      <div className="border-b border-slate-200/60 bg-white/80 backdrop-blur-sm px-6 py-3 sticky top-0 z-10">
        <h1 className="text-lg font-bold text-slate-800 tracking-tight flex items-center gap-2 mb-3">
          <FileText className="w-4 h-4 text-blue-500" />
          Abstracts
        </h1>
        <div className="flex gap-1">
          {(['per-paper', 'synthesis'] as Tab[]).map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={cn(
                'px-4 py-1.5 rounded-lg text-[13px] font-medium capitalize transition-colors',
                tab === t
                  ? 'bg-blue-600 text-white shadow-sm'
                  : 'text-slate-500 hover:bg-slate-100',
              )}
            >
              {t === 'per-paper' ? 'Per Paper' : 'Synthesis'}
            </button>
          ))}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {tab === 'per-paper' ? <PerPaperTab /> : <SynthesisTab />}
      </div>
    </div>
  )
}
